name: S3 sync action 

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: github-actions
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync S3 bucket
        run: aws s3 sync ./files s3://${{ secrets.S3_BUCKET_NAME }} --delete